spring:
  application:
    name: spring-ai-assistent
  profiles:
    active: ollama
  mvc:
    static-path-pattern: /**
---
spring:
  config:
    activate:
      on-profile: openai
  ai:
    openai:
<<<<<<< HEAD
      api-key: ${OPENAI_API_KEY}
       
=======
      api-key: ${OPENAI_API_KEY} 
>>>>>>> 95bb83c7f58a929220b0d9b9ecf6f4785b4317c2
    vectorstore:
      qdrant:
       host: ${QDRANT_HOST:localhost}
       port: ${QDRANT_PORT:6334}
       collection-name: insurance  
       initialize-schema: true
---
spring:
  config:
    activate:
      on-profile: ollama
  ai:
    ollama:
      chat:
        model: llama3.2
   
