spring:
  application:
    name: spring-ai-assistent
  profiles:
    active: production, mcp
thinkenterprise:
  exception: false

---
spring:
  config:
    activate:
      on-profile: mcp
  ai:
    mcp:
      client:
        enabled: true
        name: insurance-company-tool-mcp-client
        version: 1.0.0
        request-timeout: 30s
        type: SYNC  
        sse:
          connections: 
            webmvc-mcp-server:
              url: http://localhost:8081
#              sse-endpoint: /mcp/messages
---
spring:
  config:
    activate:
      on-profile: noMcp
  ai:
    mcp:
      client:
        enabled: false
---
spring:
  config:
    activate:
      on-profile: production
  mvc:
    static-path-pattern: /**
  docker:
    compose:
      enabled: true
      stop:
        command: down
        arguments:
        - -v
      start:
        command: up
  ai:   
    openai:
      api-key: ${OPENAI_API_KEY}
      chat:
        options:
          tool-names:
          - get_ProductDetailsByCustomer
          internal-tool-execution-enabled: true
    chat:
      observations:
        log-completion: false
        log-prompt: false
        include-error-logging: false
      client:
        observations:
          log-prompt: false
        
    vectorstore:
      qdrant:
        host: ${QDRANT_HOST:localhost}
        port: ${QDRANT_PORT:6334}
        collection-name: insurance  
        initialize-schema: true
      observations:
        log-query-response: false
    
management:
  endpoints:
    access:
      default: unrestricted
    web:
      exposure:
        include: "*"
  tracing:
    sampling:
      probability: 1.0
    enabled: true
  observations:
    annotations:
      enabled: true   
---
spring:
  config:
    activate:
      on-profile: test
  ai:
    ollama:
      init:
        pull-model-strategy: always
        embedding:
          additional-models:
            - mxbai-embed-large
      chat:
        model: llama3.2
        options:
          tool-names:
          - get_ProductDetailsByCustomer
          internal-tool-execution-enabled: true          
    vectorstore:
      qdrant:
        collection-name: insurance  
        initialize-schema: true
  
