thinkenterprise:
  exception: false
logging:
  level:
    "[org.apache.pdfbox]": ERROR
spring:
  application:
    name: spring-ai-assistent
  profiles:
    active:
    - NOP
  docker:
    compose:
      enabled: true
      stop:
        command: down
      start:
        command: up
  ai:
    tools:
      throw-exception-on-error: true
    ollama:
      chat:
        model: llama3.2
        internal-tool-execution-enabled: true
        temperature: 0.7
        num-ctx: 2048
        num-predict: 512
      base-url: http://localhost:11434
      embedding:
        model: mxbai-embed-large        
      init:
       pull-model-strategy: always
       embedding:
         additional-models:
          - mxbai-embed-large
    vectorstore:
      qdrant:
        collection-name: insurance  
        initialize-schema: true
    mcp:
      client:
        enabled: false
---
spring:
  config:
    activate:
      on-profile: mcp
  ai:
    mcp:
      client:
        enabled: true
        initialized: false
        name: insurance-company-tool-mcp-client
        version: 1.0.0
        request-timeout: 30s
        type: SYNC
        streamable-http:
          connections:
            webmvc-mcp-server:
              url: http://localhost:8081