server:
  port: 8081
thinkenterprise:
  exception: false
spring:
  ai:
    mcp:
      server:
        name: webmvc-mcp-server
        version: 1.0.0
        protocol: streamable
        type: SYNC
        instructions: "This server provides customer details tools"
        capabilities:
          tool: true
          resource: false
          prompt: false
          completion: false